osx_image: xcode10.2
xcode_project: KeePassKit.xcodeproj
language: objective-c

env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
    #- TEST_TYPE=tvOS

before_install:
- |
  if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
    carthage bootstrap --platform $TEST_TYPE
    gem install xcpretty --no-document --quiet
  fi

script:
- |
  if [ "$TEST_TYPE" = iOS ]; then
    set -o pipefail
    xcodebuild test -scheme "KeePassKit iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty -c
  elif [ "$TEST_TYPE" = macOS ]; then
    set -o pipefail
    xcodebuild test -scheme "KeePassKit macOS" -sdk macosx | xcpretty -c
  elif [ "$TEST_TYPE" = tvOS ]; then
    set -o pipefail
    xcodebuild test -scheme "KeePassKit tvOS" -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV" | xcpretty -c
  fi
